name: stock_alert_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_typeahead: ^4.3.7
  flutter_keyboard_visibility: ^5.0.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  uuid: ^4.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
